title: The Day Dreamer
theme: minima
author: GitHub User
email: neha62399877@github.com
description: > stop wasting the time its the time to do the write things instead of making fun do some hardwork.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username: https://github.com/neha2921  # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
